### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by kensuka21** [MaG21/curry#10]
<img width="528" alt="screen shot 2017-10-11 at 6 30 54 pm" src="https://user-images.githubusercontent.com/10549149/31470083-d7226d84-ae90-11e7-940a-5977dc3da410.png">

**Comment by MaG21** [comment]
I'll look into it ASAP. Thanks

**Comment by MaG21** [comment]
The service is back online again. For more information refer to the commit message.

Thanks for taking the time to letting us know about this issue.
