### ISSUE TITLE
Add more banks rates

### ISSUE THREAD

**Issue by aterronb** [MaG21/curry#11]
http://www.bancocaribe.com.do
http://www.scotiabank.com/do/es/1,,8924,00.html

**Comment by MaG21** [comment]
These banks don't provide the necessary information to be considered as good candidates. Banco Caribe updates the rates randomly. Scotiabank is not that precise when it comes to EURO, likewise http://www.apap.com.do lacks EURO rates.

The only bank worthy of consideration is Asociacion Cibao, they update the rates on a daily basis and provide both DOLLAR and EURO rates. http://www.acap.com.do
