### ISSUE TITLE
http://api.marcos.do/rates is not working

### ISSUE THREAD

**Issue by dison2030** [MaG21/curry#16]
http://api.marcos.do/rates is not working

**Comment by MaG21** [comment]
For the changes to take effect on api.marcos.do @eneldoserrata has to update their service.

**Comment by MaG21** [comment]
One thing though, there's a pending change that once applied will allow this application to correctly parse Lopez de Haro rates.

For now everything is in order (unless you rely on BLH rates)

**Comment by dison2030** [comment]
still not working, Internal Server Error

http://api.marcos.do/rates

**Comment by MaG21** [comment]
Bad News
http://api.marcos.do/rates is a service provided by a third party.
I spoke with the person that owns api.marcos.do and he said he will not longer maintain the service.

In light of the events I'm planning on providing this app as a service elsewhere. So there's that. However I suggest you deploy this app on your on servers in the mean time.

Ideas or propositions are welcome.

**Comment by dison2030** [comment]
i will create my own scrapy i can't depend on this.

Thanks.
